# Default values for tpcds-benchmark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Image registry
  registry: registry-cn-beijing-vpc.ack.aliyuncs.com
  # -- Image repository
  repository: ack-demo/spark-tpcds-benchmark
  # -- Image tag
  tag: 3.5.3-0.1
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image pull secrets
  pullSecrets: []
  # - name: pull-secret

oss:
  # -- OSS bucket
  bucket: example-bucket
  # -- OSS region
  region: cn-beijing
  # -- OSS endpoint
  endpoint: oss-cn-beijing-internal.aliyuncs.com

benchmark:
  # -- Scale factor
  scaleFactor: 3072
  # -- Number of partitions
  numPartitions: 640

# -- Specifies which SDK to use when accessing OSS.
# Available options are:
#   1. hadoop-aliyun (Ref: https://apache.github.io/hadoop/hadoop-aliyun/tools/hadoop-aliyun/index.html)
#   2. hadoop-aws (Ref: https://apache.github.io/hadoop/hadoop-aws/tools/hadoop-aws/index.html)
#   3. jindoSDK (Ref: https://github.com/aliyun/alibabacloud-jindodata)
sdk: hadoop-aliyun
