# Default values for tpcds-benchmark.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # -- Image registry
  registry: registry-cn-beijing-vpc.ack.aliyuncs.com
  # -- Image repository
  repository: ack-demo/spark-tpcds-benchmark
  # -- Image tag
  tag: 3.5.3-0.1
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image pull secrets
  pullSecrets: []
  # - name: pull-secret

oss:
  # -- OSS bucket
  bucket: example-bucket
  # -- OSS endpoint
  endpoint: oss-cn-beijing-internal.aliyuncs.com

benchmark:
  # -- Scale factor
  scaleFactor: 3072
  # -- Number of iterations
  numIterations:  1
  # -- Whether to optimize queries
  optimizeQueries: false
  # -- Filter queries, will run all if empty
  queries: []
  # - q70-v2.4
  # - q82-v2.4
  # - q64-v2.4
